### ISSUE TITLE
NullPointerException if an image don't have a repoTags

### ISSUE THREAD

**Issue by cedricoudot** [tdomzal/junit-docker-rule#32]
Hello,

I just find a little bug.

If an image don't have a repo tags, there's a null pointer and the docker container is not runned.

Here's the produced stack : 

java.lang.ExceptionInInitializerError: null
    at pl.domzal.junit.docker.rule.DockerRule.imageAvaliable(DockerRule.java:152)
    at pl.domzal.junit.docker.rule.DockerRule.<init>(DockerRule.java:72)
    at pl.domzal.junit.docker.rule.DockerRuleBuilder.build(DockerRuleBuilder.java:37)

The code : (DockerRule line 152)

List<Image> listImages = dockerClient.listImages(ListImagesParam.danglingImages(false));
for (Image image : listImages) {
// IMAGE.REPOTAGS() IS NULL HERE
    if (image.repoTags().contains(imageNameWithTag)) {
           .....
    }
}

ListImagesParam.danglingImages(false), returns an image with a null repoTags, don't know why.
In this case, your code crash, leave the loop and docker container is not launched.

Thank you, regards

Cédric

**Comment by cedricoudot** [comment]
the command "docker images -f dangling=false" returns images with TAG <none> !!

I think here's your problem

**Comment by tdomzal** [comment]
Hi,
Thanks for reporting.

You mean:
"docker images -f dangling=false" returns images **without** TAG
?

Looks you're right.
Which version do you use ? 0.1 or 0.2-SNAPSHOT ?

Tomek

**Comment by tdomzal** [comment]
@cedricoudot 
Fixed in 0.2-SNAPSHOT.
Let me know if you need fix to be backported to 0.1.x

**Comment by cedricoudot** [comment]
Hello,

Yes, I mean "docker images -f dangling=false" returns images without TAG ! 

I'm using your last release, so the 0.1

Can you please backport ?

Thank you very much, 

Cédric

**Comment by tdomzal** [comment]
Version 0.1.1 deployed to maven central.
Tomek
P.S. Thanks for using!.
I'll be grateful for starring if you find it useful ;).

**Comment by cedricoudot** [comment]
Thank you Tomek ! I'll stare it right now ! Thanks !
