### ISSUE TITLE
0.3 release

### ISSUE THREAD

**Issue by csabakoncz** [tdomzal/junit-docker-rule#40]
Could we have an 0.3 release on Maven Central?

Right now our Jenkins is running in a container and thus the waitForTcpPort conditions which try to connect to ports exposed on the Docker host fail when running the tests in the CI.

The new StartCondition + TcpPortChecker classes from the SNAPSHOT version would come handy (I could use them to connect directly to the container port).

Unfortunately my company's Nexus is not mirroring the Sonatype repo, so I can not use the snapshot from there.

BTW, thank you for this great library!

Csaba

**Comment by tdomzal** [comment]
Sure,
Nothing spectacular happened from 0.2 but it was quite some time ago so I'll build and deploy 0.3 in a moment.

Regarding WaitFor.tcpPort(...)...
__Please note in some cases you can't rely on it - it depends of platform and docker host configuration options__ so make sure it will work in your case.
See javadoc comments for details:
https://github.com/tdomzal/junit-docker-rule/blob/master/src/main/java/pl/domzal/junit/docker/rule/WaitFor.java#L72

Anyway, I'm glad you find my library helpful - please give it a star if you do... 😉

**Comment by tdomzal** [comment]
Done,
It should be available in repo in few hours.

**Comment by csabakoncz** [comment]
Thank you!

As I said, the special about our CI is that Jenkins itself runs as a container that has `/var/run/docker.sock` from the Docker host mounted, and, as a result, it creates sibling containers.

Thank you for the warning, right now I seem to run without problems:
```
21:24:37.577   [main] INFO  p.d.junit.docker.rule.DockerRule - container mysql:5.6 created, id  [...]
21:24:37.996   [main] INFO  p.d.j.docker.rule.WaitForContainer - wait for tcp port check '172.17.0.9:[[3306]]' started

[...]

21:24:51.008   [main] INFO  p.d.j.docker.rule.WaitForContainer - wait for tcp port check '172.17.0.9:[[3306]]' - condition met
21:24:51.008   [main] INFO  p.d.junit.docker.rule.DockerRule - 10f0138147de docker host: localhost, ip: 172.17.0.9, gateway: 172.17.0.1, exposed ports: {3306/tcp=[PortBinding{hostIp=0.0.0.0, hostPort=32782}]}
``` 

According to the log timestamps the wait took over 13 seconds - it works!
