### ISSUE TITLE
JUnit 5 support 

### ISSUE THREAD

**Issue by peter-ponzel** [tdomzal/junit-docker-rule#46]
hello,
from what I read so far `@Rule` and `TestRule` won't work anymore,
instead one should use `@ExtendWith(SomeExtension.class)` and `AfterEachCallback` & `BeforeEachCallback`
are you planning on supporting this ?
best regards,
peter

**Comment by tdomzal** [comment]
Hi,
As version 5 will gradually replace version 4 this is definitely something I'd like to implement.
Only problem is I don't currently use version 5 so this would require some off-time extra work from me.
But will look into it soon.
Tomek
